#!/bin/sh -e

cd "$(dirname "$0")"

mkdir -p solutionsL
for f in data/problemsL/*.mdl; do
    trace_filename=$(basename "$f"|sed s/_tgt.mdl/.nbt/)
    echo "Solving $f"
    stack exec -- time icfpc2018 "$f" "solutionsL/$trace_filename"
done
